export const CHANGE_COMPANY_SEARCH_TERM = 'CHANGE_COMPANY_SEARCH_TERM';
export const CLEAR_COMPANY_SEARCH_TERM = 'CLEAR_COMPANY_SEARCH_TERM';

export const LOAD_COMPANY_DETAILS_START = 'LOAD_COMPANY_DETAILS_START';
export const LOAD_COMPANY_DETAILS_SUCCESS = 'LOAD_COMPANY_DETAILS_SUCCESS';
export const LOAD_COMPANY_DETAILS_FAILED = 'LOAD_COMPANY_DETAILS_FAILED';

export const LOAD_COMPANY_PRICE_START = 'LOAD_COMPANY_PRICE_START';
export const LOAD_COMPANY_PRICE_SUCCESS = 'LOAD_COMPANY_PRICE_SUCCESS';
export const LOAD_COMPANY_PRICE_FAILED = 'LOAD_COMPANY_PRICE_FAILED';

export const ADD_COMPANY_TO_FAVORITES = 'ADD_COMPANY_TO_FAVORITES';
export const REMOVE_COMPANY_FROM_FAVORITES = 'REMOVE_COMPANY_FROM_FAVORITES';
export const CLEAR_COMPANY_FAVORITES = 'CLEAR_COMPANY_FAVORITES';
